image: node:10

before_script:
  - "which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)"
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
  - chmod 0600 -R ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh bogdan.calapod@tech-lounge.ro 'cd /home/bogdan.calapod/sric && ./home/bogdan.calapod/.nvm/versions/node/v8.9.4/bin/npm run build && cp -r public/* /var/www/sric.cs.pub.ro/'
